version: '3.9'

services:
  server:
    build: ./server
    volumes: 
      - "./server:/server/"
    # ports:
    #   - "5001:5000"
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    build: ./Nginx
    depends_on:
      - server
    ports:
      - "8080:8080"
    networks:
    - app-network

  mongo:
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - app-network

networks:
    app-network:
        driver: bridge